site_name: Documentação linguagem G2DL
theme:
  name: material

nav:
  - Início: index.md
  - Léxico: lexer.md
  - Sintaxe: parser.md
  - AST: ast.md
  - Execução: execution.md

plugins:
  - search
  - pdf-export:
      combined: true
      media_type: print
